<?php

require_once __DIR__ . "/util.php";

/**
 * Handles the database connection.
 *
 * @author albertowd
 */
class DBConnection
{
    /**
     * Database connection class.
     * @var PDO
     */
    private static $connection = null;

    /**
     * Atempt a connection with the database.
     * @return bool
     */
    public static function connect()
    {
        // If it's not connected, try it.
        if (static::$connection == null) {
            try {
                static::$connection = new PDO("mysql:charset=utf8;dbname=setup_share;host=localhost", "setup_user", "setup_2018");
                static::$connection->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            } catch (PDOException $ex) {
                echo BR . $ex->getMessage();
                static::$connection = null;
            }
        }

        return static::isConnected();
    }

    /**
     * If it's connected, disconnect.
     */
    public static function disconnect()
    {
        if (static::isConnected()) {
            static::$connection = null;
        }
    }

    /**
     * Verifies if it's connected.
     * @return bool
     */
    public static function isConnected()
    {
        return static::$connection != null;
    }

    /**
     * Make a simple query.
     *
     * @param string $sql
     *           Simple query.
     * @return PDOStatement|null
     */
    public static function query(string $sql)
    {
        $stmt = null;
        if (static::isConnected()) {
            $start = time();
            try {
                $stmt = static::$connection->query($sql);
                if (isTest()) {
                    $elapsed = time() - $start;
                    echo BR . "Executed ({$elapsed}s): $sql";
                }
            } catch (PDOException $ex) {
                error_log($ex->getMessage());
            }
        } else {
            error_log("Trying to query without being connected.");
        }
        return $stmt;
    }

    /**
     * Return the last insert id generated by the database.
     * @return int
     */
    public static function lastInsertId()
    {
        if (static::isConnected()) {
            return static::$connection->lastInsertId();
        } else {
            return 0;
        }
    }

    /**
     * Prepare a query.
     *
     * @param string $sql
     *           Prepared query.
     * @return PDOStatement|null
     */
    public static function prepare(string $sql, array $values)
    {
        $stmt = null;
        if (static::isConnected()) {
            $start = time();
            try {
                $stmt = static::$connection->prepare($sql);
                $stmt->execute($values);
                if (isTest()) {
                    $elapsed = time() - $start;
                    echo BR . "Executed ({$elapsed}s): $sql";
                }
            } catch (PDOException $ex) {
                error_log($ex->getMessage());
            }
        } else {
            error_log("Trying to query without being connected.");
        }
        return $stmt;
    }
}

/**
 * Connection test.
 */
if (isset($_REQUEST["test"]) && DBConnection::connect()) {
    echo BR . (DBConnection::isConnected() ? "Connection tested with success." : "No database connection.");
}
